In [3]:
import numpy as np

# Question 1
Create this array of exactly 5 evenly-spaced values:
```
array([0.  , 0.25, 0.5 , 0.75, 1.  ])
```

In [4]:
arr = np.linspace(0, 1, 5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Question 2
Create this evenly-spaced 1D array:
```
array([  0,   5,  10,  15,  20,  25])
```

In [5]:
arr = np.arange(0, 26, 5)
arr

array([ 0,  5, 10, 15, 20, 25])

# Question 3
Allocate an uninitialized block of memory for a (4, 3) array — the fastest possible allocation. You will fill every cell before reading it.

Goal:
- reserve uninitialized memory
- shape: (4, 3)  |  dtype: float64
- ⚡ Fastest allocation — no fill step
- ⚠  You must overwrite every cell before reading!

In [6]:
arr = np.empty((4,3))
arr[:] = 0
print(type(arr[1][1])) # check dtype
arr

<class 'numpy.float64'>


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Question 4
Create exactly this 1D array:
```
array([3, 14,  7, 21,  9])
```

In [7]:
arr = np.array([3, 14, 7, 21, 9])
arr

array([ 3, 14,  7, 21,  9])

# Question 5
Create this 2D matrix:
```
array([[1., 1., 1., 1., 1.],  
       [1., 1., 1., 1., 1.]])  
```
shape: (2, 5)

In [8]:
arr = np.ones((2, 5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Question 6
Create a random integer array of this shape with values in [1, 10). Your values will differ!

Example output (your values will differ):
```
array([[4, 9, 2, 7, 1],  
       [8, 5, 3, 6, 4]])
```
shape: (2, 5)  |  dtype: int64  |  range: [1, 10)

In [9]:
arr = np.random.randint(1, 10, size = (2, 5))
arr

array([[2, 9, 7, 6, 3],
       [1, 1, 6, 6, 2]], dtype=int32)

# Question 7
Create this identity matrix:  
```
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
```
shape: (4, 4)

In [10]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Question 8
Create a random float array of this exact shape. Your values will differ — that is expected!  
Example output (your values will differ):  
```
array([[0.37, 0.95, 0.73],
       [0.60, 0.16, 0.06],
       [0.84, 0.22, 0.48]])
```
shape: (3, 3)  |  dtype: float64  |  values in [0, 1)

In [11]:
arr = np.random.random((3, 3)) # I do not know how to get only 2 digits to show without using randint
arr

array([[0.75757942, 0.29468371, 0.21489986],
       [0.62759346, 0.52798215, 0.54097326],
       [0.17868175, 0.95793356, 0.43183455]])

In [12]:
# method with randint for 2 digits after the decimal
arr = np.random.randint(0, 100, (3, 3)).astype(float) / 100
print(type(arr[1][1]))
arr

<class 'numpy.float64'>


array([[0.32, 0.98, 0.33],
       [0.43, 0.4 , 0.6 ],
       [0.52, 0.1 , 0.11]])

# Question 9
Create this constant-filled 2D matrix:
```
array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])
```
shape: (3, 3)  |  fill_value = 9

In [13]:
arr = np.full((3, 3), 9)
arr

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# Question 10
Create this 2D matrix:
```
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
```
shape: (3, 4)

In [14]:
arr = np.zeros((3, 4), dtype = float)
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])