In [1]:
import numpy as np

# Question 1
Given a = np.array([1, np.e, np.e**2]) — what does np.log(a) return?  
```
natural log:  
```
>ln(1)=0  
>ln(e)=1  
>ln(e²)=2  

array([?, ?, ?])

In [3]:
a = np.array([1, np.e, np.e**2])
np.log(a) # returns [0, 1, 2] because that is the natural log for each of the numbers in the array

array([0., 1., 2.])

# Question 2
Given a = np.array([10, 20, 30]) and b = np.array([1, 2, 3]) — what does np.subtract(a, b) return?  
array([?, ?, ?])

In [4]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
np.subtract(a, b) # returns the numbers in array a minus the numbers in array b, giving [9, 18, 27]

array([ 9, 18, 27])

# Question 3
Given a = np.array([0, 1, 2]) — what does np.exp(a) return? (round to 2 dp) 

- e⁰=1
- e¹≈2.72
- e²≈7.39
  
array([?, ?, ?])

In [8]:
a = np.array([0, 1, 2])
np.exp(a) # returns [1, 2.72, 7.39], the value of e^x for each number x in the array

array([1.        , 2.71828183, 7.3890561 ])

# Question 4
Given A = np.array([[1,2],[3,4]]) and B = np.array([[1,0],[0,1]]) — what does A.dot(B) return?  
B is the identity matrix
```
array([[?, ?],
       [?, ?]])
```

In [7]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[0,1]])
A.dot(B) # returns the dot product of the two arrays, [[1, 2], [3, 4]]

array([[1, 2],
       [3, 4]])

### Dot Product Explanation
![Dot Product](Dot_Product.PNG)  
In our case, we have:
```
  ⌈ 1  2 ⌉       ⌈ 1  0 ⌉        ⌈ 1×1 + 2×0   1×0 + 2×1 ⌉       ⌈ 1  2 ⌉
            •              =                               =  
  ⌊ 3  4 ⌋       ⌊ 0  1 ⌋        ⌊ 3×1 + 4×0   3×0 + 4×1 ⌋       ⌊ 3  4 ⌋
```

# Question 5
Given a = np.array([0, np.pi/2, np.pi]) — what does np.sin(a) return? (round to 1 dp)  
- sin(0)=0
- sin(π/2)=1
- sin(π)≈0
  
array([?, ?, ?])

In [10]:
a = np.array([0, np.pi/2, np.pi])
np.sin(a) # returns [0, 1, 0], the value of sin(x) for each number x in the array
# ignore the last one, as it is an approximation of pi and therefore not 100% precise

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

# Question 6
Given a = np.array([10.0, 20.0, 30.0]) and b = np.array([2.0, 4.0, 5.0]) — what does np.divide(a, b) return?  
array([?, ?, ?])

In [11]:
a = np.array([10.0, 20.0, 30.0])
b = np.array([2.0, 4.0, 5.0])
np.divide(a, b) # returns [5, 5, 6], the results of dividing the values in a by the values in b

array([5., 5., 6.])

# Question 7
Given a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) — what does np.add(a, b) return?  
array([?, ?, ?])


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.add(a, b) # returns [5, 7, 9], the result of adding the values in a with the values in b

array([5, 7, 9])

# Question 8
Given a = np.array([2, 3, 4]) and b = np.array([10, 10, 10]) — what does np.multiply(a, b) return?  
array([?, ?, ?])

In [13]:
a = np.array([2, 3, 4])
b = np.array([10, 10, 10])
np.multiply(a, b) # returns [20, 30, 40], the result of multiplying the values in a with the values in b

array([20, 30, 40])

# Question 9
Given a = np.array([0, 1, 4, 9, 16]) — what does np.sqrt(a) return?  
array([?, ?, ?, ?, ?])

In [14]:
a = np.array([0, 1, 4, 9, 16])
np.sqrt(a) # returns [0, 1, 2, 3, 4], or the square roots of each value in a

array([0., 1., 2., 3., 4.])