In [3]:
import numpy as np

# Question 1
Given b = np.array([[1,2,3],[4,5,6]]) — what does b[1, 2] return?

In [27]:
b = np.array([[1,2,3],[4,5,6]])
b[1, 2] # returns 6. it opens the index 1 list, and then the index 2 value in that list

np.int64(6)

# Question 2
Given a = np.array([3,1,4,1,5,9]) — what does a look like after a.sort()?  
array([?, ?, ?, ?, ?, ?])


In [30]:
a = np.array([3,1,4,1,5,9])
a.sort() # pretty straightforward (pun intended)
print(a)

[1 1 3 4 5 9]


# Question 3
Given a = np.array([1,2,3]) and v = a.view() — if you do v[0] = 99, what does a[0] return?  
view shares memory  
a[0] = ?

In [32]:
a = np.array([1,2,3])
v = a.view()
v[0] = 99
a[0] # returns 99. view shows you the array, and changing what is in the view will therefore change what it is looking at

np.int64(99)

# Question 4
Given a = np.array([1,2,3]) and c = np.copy(a) — if you do c[0] = 99, what does a[0] return?  
copy is independent  
a[0] = ?

In [33]:
a = np.array([1,2,3])
c = np.copy(a)
c[0] = 99
a[0] # returns 1, since copy does not view the original array, but copies it to a new one

np.int64(1)

# Question 5
Given b = np.array([[3,1],[4,2]]) — what does b look like after b.sort(axis=0)?  
sorts each column independently  
```
array([[?, ?],
       [?, ?]])
```

In [34]:
b = np.array([[3,1],[4,2]])
b.sort(axis=0)
b # returns [[3, 1], [4, 2]] sorts the columns ONLY. turns out it was already sorted by column

array([[3, 1],
       [4, 2]])

# Question 6
Given b = np.array([[1,2,3],[4,5,6],[7,8,9]]) — what does b[0:2, 1] return?  
array([?, ?])


In [36]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[0:2, 1] # returns [2, 5]. lists 0-2, not inclusive, with the first index of each

array([2, 5])

# Question 7
Given b = np.array([[1,2],[3,4],[5,6]]) — what does b[[0,2], [1,0]] return?  
fancy indexing picks [row0,col1] and [row2,col0]  
array([?, ?])

In [38]:
b = np.array([[1,2],[3,4],[5,6]])
b[[0,2], [1,0]] # same as a condition, will give [5, 2], since it moves first to the right and then down

array([2, 5])

# Question 8
Given a = np.array([1,5,3,8,2]) — what does a[a < 4] return?  
array([?, ?, ?])

In [40]:
a = np.array([1,5,3,8,2])
a[a < 4] # [1, 3, 2], all values below 4

array([1, 3, 2])

# Question 9
Given a = np.array([10,20,30,40,50]) — what does a[2] return?  


In [41]:
a = np.array([10,20,30,40,50])
a[2] # index 2, returns 30

np.int64(30)

# Question 10
Given a = np.array([10,20,30,40,50]) — what does a[1:4] return?  
array([?, ?, ?])

In [43]:
a = np.array([10,20,30,40,50])
a[1:4] # indices 1 through 4, not inclusive, returns [20, 30, 40]

array([20, 30, 40])

# Question 11
Given a = np.array([1,2,3,4,5]) — what does a[::-1] return?  
array([?, ?, ?, ?, ?])


In [44]:
a = np.array([1,2,3,4,5])
a[::-1] # all indices, step -1, returns [5, 4, 3, 2, 1]

array([5, 4, 3, 2, 1])