In [2]:
import numpy as np

# Question 1
Given a = np.array([1,2,3,4]) — what does np.insert(a, 2, 99) return?  
inserts 99 at index 2  
array([?, ?, ?, ?, ?])

In [4]:
a = np.array([1,2,3,4])
np.insert(a, 2, 99) # inserts but does not overwrite values. returns [1, 2, 99, 3, 4]

array([ 1,  2, 99,  3,  4])

# Question 2
Given a = np.array([[1,2,3],[4,5,6]]) — what does a.ravel() return?  
array([?, ?, ?, ?, ?, ?])


In [11]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel() # flattens all dimensions into one
# returns [1, 2, 3, 4, 5, 6]

array([1, 2, 3, 4, 5, 6])

# Question 3
Given a = np.arange(6) — what does a.reshape(2, 3) return?  
```
array([[?, ?, ?],
       [?, ?, ?]])
```      

In [6]:
a = np.arange(6)
a.reshape(2, 3) # returns new array with 2 rows and three columns, [[0, 1, 2], [3, 4, 5]]

array([[0, 1, 2],
       [3, 4, 5]])

# Question 4
Given a = np.arange(8).reshape(4,2) — what does np.vsplit(a, 2) return?  
splits into 2 sub-arrays of shape (2, 2)  
[array([[?,?],[?,?]]), array([[?,?],[?,?]])]

In [9]:
a = np.arange(8).reshape(4,2)
np.vsplit(a, 2) # splits array a into 2 arrays. goes in order of numbers - vertical split, like argmin and argmax.
# basically takes the rows and splits them based on the number of times requested
# must be a divisor of the total n umber of rows
# returns [[0, 1], [2, 3]], [[4, 5], [6, 7]]

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]])]

# Question 5
Given a = np.array([1,2,3,4,5,6]) — what does np.hsplit(a, 3) return?  
splits into 3 equal parts  
[array([?,?]), array([?,?]), array([?,?])]

In [10]:
a = np.array([1,2,3,4,5,6])
np.hsplit(a, 3) # similar to vsplit, only horizontally, meaning it will split the columns
# returns [1, 2], [3, 4], [5, 6]

[array([1, 2]), array([3, 4]), array([5, 6])]

# Question 6
Given a = np.array([1,2,3]) and b = np.array([4,5,6]) — what does np.vstack([a, b]) return?  
shape: (2, 3)  
```
array([[?, ?, ?],
       [?, ?, ?]])
```

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack([a, b]) # the opposite of vstack. will stack rows vertically
#returns [[1, 2, 3], [4, 5, 6]] as one single array

array([[1, 2, 3],
       [4, 5, 6]])

# Question 7
Given a = np.array([1,2,3]) and b = np.array([4,5,6]) — what does np.hstack([a, b]) return?  
array([?, ?, ?, ?, ?, ?])


In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack([a, b]) # similar to vstack, but will place them side by side horizontally
# returns [1, 2, 3, 4, 5, 6] as one single array

array([1, 2, 3, 4, 5, 6])

# Question 8
Given a = np.array([10,20,30,40,50]) — what does np.delete(a, 2) return?  
array([?, ?, ?, ?])

In [16]:
a = np.array([10,20,30,40,50])
np.delete(a, 2) # deletes index 2 from array a
# returns [10, 20, 40, 50]

array([10, 20, 40, 50])

# Question 9
Is a.reshape(3,4) valid if a = np.arange(10)? What about a.reshape(2,5)?  
total elements must match  
>reshape(3,4): ?  
>reshape(2,5): ?

a = np.arange(10)
> a.reshape(2,5) Valid  
> a.reshape(3,4) Not Valid

The shape needs to correspond with the total number of values

# Question 10
Given a = np.array([[1,2,3],[4,5,6]]) — what does a.T return?  
shape becomes (3, 2)  
```
array([[?, ?],
       [?, ?],
       [?, ?]])
```

In [17]:
a = np.array([[1,2,3],[4,5,6]])
a.T # can also be written a.transpose()
# transposing flips columns and rows, so yuoll see here [[1, 4], [2, 5], [3, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

# Question 11
Given a = np.array([1,2,3]) — what does np.append(a, [4,5]) return?  
array([?, ?, ?, ?, ?])

In [18]:
a = np.array([1,2,3])
np.append(a, [4,5]) # appends [4, 5] to the end of the array
# returns [1, 2, 3, 4, 5]

array([1, 2, 3, 4, 5])

# Question 12
Given a = np.array([1,2,3]) and b = np.array([4,5,6]) — what does np.concatenate([a, b]) return?  
array([?, ?, ?, ?, ?, ?])

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate([a, b])
# while vstack and hstack can create more dimensions automatically, concatenate requires the dimensoin to already exist
# np.concatenate([a, b], axis = 1), while vstack will return a 2 dimensional array
# returns [1, 2, 3, 4, 5, 6]

array([1, 2, 3, 4, 5, 6])

# Question 13
Given a = np.array([1,2,3]) and b = np.array([4,5,6]) — what does np.column_stack([a, b]) return?  
shape: (3, 2)  
```
array([[?, ?],
       [?, ?],
       [?, ?]])
```

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.column_stack([a, b])
# if the arrays given are both multidimensional, this will effectively do the same as transpose and then hstack
# transpose does not do anything to single dimensional arrays, so single dimensional arrays for that method will return a one dimensional array

# interestingly, vstack and then transpose WILL actually give you the same result as column_stack, although in a different manner
# vstack creates a view, while column_stack creates a brand new array

# will return [[1, 4], [2, 5], [3, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])