In [1]:
import numpy as np

# Question 1
Given a = np.array([3, 1, 7, 2, 9, 4]) — what does a.argmin() and a.argmax() return?  
returns the index, not the value  
>argmin: ?  
>argmax: ?

In [20]:
a = np.array([3, 1, 7, 2, 9, 4])
print(f'a.argmin() = {a.argmin()}') # returns 1, the index of the smallest number
print(f'a.argmax() = {a.argmax()}') # returns 4, the index of the largest number

a.argmin() = 1
a.argmax() = 4


# Question 2
Given a = np.array([1,2,3]) and b = np.array([1,2,3]) — what does np.array_equal(a, b) return?  
?

In [7]:
a = np.array([1,2,3])
b = np.array([1,2,3])
np.array_equal(a, b) # returns True, because they are equal

True

# Question 3
Given a = np.array([2,4,4,4,5,5,7,9]) — what does np.std(a) return?  
?.?

In [10]:
a = np.array([2,4,4,4,5,5,7,9])
np.std(a) # returns 2.0

np.float64(2.0)

### Mean, Variance, and Standard Deviation Equations
![mean_variance_std.PNG](mean_variance_std.PNG)  
In our case, we have a sum of: 40  
And a len of: 8  
Meaning, the average, or mean, is: 40 / 8 = 5  
So now we have [2-5, 4-5, 4-5, 4-5, 5-5, 5-5, 7-5, 9-5] = [-3, -1, -1, -1, 0, 0, 2, 4]  
Square each of those: [9, 1, 1, 1, 0, 0, 4, 16]  
Add them up: 32  
Now we divide by the number of values, which is 8: 4  
The square root of that gives us the **Standard Deviation**: 2.0

# Question 4
Given a = np.array([2,4,4,4,5,5,7,9]) — what does np.var(a) return? How does it relate to std?  
var = std²  
?.?

In [11]:
a = np.array([2,4,4,4,5,5,7,9])
np.var(a) # will return 4.0, which is the square of the standard deviation, as calculated above

np.float64(4.0)

# Question 5
Given a = np.array([1,2,3]) and b = np.array([1,5,3]) — what does a == b return?  
array([?, ?, ?])

In [12]:
a = np.array([1,2,3])
b = np.array([1,5,3])
a == b # returns [True, False, True], as each index is compared between the two arrays

array([ True, False,  True])

# Question 6
Given x = np.array([1,2,3]) and y = np.array([2,4,6]) — what is the off-diagonal value of np.corrcoef(x, y)?  
perfectly proportional arrays  
r = ?.?

In [13]:
x = np.array([1,2,3])
y = np.array([2,4,6])
np.corrcoef(x, y) # the diagonal is always 1.0 for all values across it, and the Pearson Correlation Coefficient will be explained below

array([[1., 1.],
       [1., 1.]])

### Pearson Correlation Coefficient
$$\begin{bmatrix} r_{xx} & r_{xy} \\ r_{yx} & r_{yy} \end{bmatrix}$$

$r_{xx}$ and $r_{yy}$ are always equal to 1, since the two arrays correlate perfectly with themselves  
$r_{xy}$ and $r_{yx}$ are the correlation between arrays x and y, and are equal  

We start by finding the mean for both arrays:  
$$\bar{X} = \frac{a + b + c}{3} = \frac{1 + 2 + 3}{3} = 2$$  
$$\bar{Y} = \frac{d + e + f}{3} = \frac{4 + 5 + 6}{3} = 5$$  

Next we find the correlation of x with y:  
$$r_{xy} = \frac{(a - \bar{X})(d - \bar{Y}) + (b - \bar{X})(e - \bar{Y}) + (c - \bar{X})(f - \bar{Y})}{\sqrt{[(a - \bar{X})^2 + (b - \bar{X})^2 + (c - \bar{X})^2] \cdot [(d - \bar{Y})^2 + (e - \bar{Y})^2 + (f - \bar{Y})^2]}}$$  
Where in our case looks like:  
$$r_{xy} = \frac{(1 - 2)(4 - 5) + (2 - 2)(5 - 5) + (3 - 2)(6 - 5)}{\sqrt{[(1 - 2)^2 + (2 - 2)^2 + (3 - 2)^2] \cdot [(4 - 5)^2 + (5 - 5)^2 + (6 - 5)^2]}} = \frac{1 + 0 + 1}{\sqrt{[(-1)^2 + 0^2 + 1^2] \cdot [(-1)^2 + 0^2 + 1^2]}} = \frac{2}{\sqrt{4}} = 1$$  

It looks complicated, but its really just plugging in the numbers, and you get an answer; the answer here being that they have a correlation coefficient of 1 with each other, meaning the output matrix will be:  
$$\begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix}$$

# Question 7
Given a = np.array([1, 5, 3, 8, 2]) — what does a > 3 return?  
array([?, ?, ?, ?, ?])


In [14]:
a = np.array([1, 5, 3, 8, 2])
a > 3 # returns [False, True, False, True, False], as each value is compared individually and returns a boolean 

array([False,  True, False,  True, False])

# Question 8
Given a = np.array([1, 2, 3, 4]) — what does a.cumsum() return?  
array([?, ?, ?, ?])


In [15]:
a = np.array([1, 2, 3, 4])
a.cumsum() # returns [1, 3, 6, 10], the cumulative sum for each index

array([ 1,  3,  6, 10])

# Question 9
Given a = np.arange(1, 6) — what does a.mean() return?  
a = [1, 2, 3, 4, 5]
?.?

In [16]:
a = np.arange(1, 6)
a.mean() # returns 3.0, the mean of the values in the array

np.float64(3.0)

# Question 10
Given a = np.array([3, 1, 7, 2, 9, 4]) — what does a.min() and a.max() return?  
>min: ?  
>max: ?

In [19]:
a = np.array([3, 1, 7, 2, 9, 4])
print(f'a.min() = {a.min()}') # returns 1, the smallest number
print(f'a.max() = {a.max()}') # returns 9, the largest number

a.min() = 1
a.max() = 9


# Question 11
Given a = np.array([[1,2],[3,4]]) — what does a.sum(axis=0) return?  
axis=0 = sum each column  
array([?, ?])

In [24]:
a = np.array([[1,2],[3,4]])
a.sum(axis=0) # returns [4, 6], the sum of the numbers in each column (axis = 0)

array([4, 6])

# Question 12
Given a = np.array([1, 3, 2, 5, 4]) — what does np.median(a) return?  
?.?

In [26]:
a = np.array([1, 3, 2, 5, 4])
np.median(a) # orders the numbers from lowest to highest, and takes the index in the middle, returning the value at that index
# in the case of an even number of values, the median will be the midpoint, or average, between the two numbers in the 2 middle indices

np.float64(3.0)