In [1]:
import numpy as np

# Homework Exercises
1. Work through the 14 exercises in the panel — one for each operator covered in Topics 07.  
2. Also write and run the argmax row+col snippet from Topic 1 with your own random array size.  
3. For each of exp, log, dot, cumsum — write at least one example of your own (different input from the lesson) and verify the result.

## Part 1
[14 Exercise Panel](https://github.com/GreatWolf155/Yosef_Greenfield_Homeworks/blob/master/Module%2003%20-%20Python%20Libraries/M03%20HW03/M03CW03%20Libs%20Q03%20Array%20Comparison%20and%20Statistics.ipynb)

## Part 2

In [10]:
np.random.seed(57)
arr = np.random.randint(0, 101, (6, 7))
arg_max = arr.argmax()

col = arg_max % arr.shape[1]
row = arg_max // arr.shape[1]

print(f'Coordinates of largest number: ({row},{col})')

Coordinates of largest number: (5,2)


## Part 3

In [20]:
a = np.random.randint(0, 2, (2, 4))
print(np.exp(a))
print()

e = np.e
a = np.array([1, e, e**2, e, 1])
print(np.log(a))
print()

A = np.array([[1,2],[1,4]])
B = np.array([[1,4],[1,3]])
print(A.dot(B))
print()

a = np.array([3, 4, 5, 1, 4])
print(a.cumsum())

[[1.         1.         1.         1.        ]
 [2.71828183 2.71828183 2.71828183 1.        ]]

[0. 1. 2. 1. 0.]

[[ 3 10]
 [ 5 16]]

[ 3  7 12 13 17]
